apiVersion : apps/v1
kind: Deployment
metadata:
  name: aji-api-qa
  namespace: flexcub-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aji-api-qa
  template:
    metadata:
      labels:
        app: aji-api-qa
    spec:
      containers:
        - name: aji-api-qa
          image: ajiqbrainx/db:resourceplanning-qa-1
          ports:
            - containerPort: 80




            