# name: FlexCub gitAction_CICD

# on:
#   push:
#     branches: development

# permissions:
#   contents: read

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#           java-version: '11'
#           distribution: 'temurin'
#     - name: Build with Gradle
#       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#       with:
#           arguments: build        
#     - name: Docker meta
#       id: meta
#       uses: docker/metadata-action@v4
#       with:
#           images: vasanthdev/flexcub
#           tags: |
#            type=raw,value=dev-api-{{date 'Y-M-D'}}
#     - name: Login to DockerHub
#       if: github.event_name != 'pull_request'
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME}}
#         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#     - name: Docker build and push
#       uses: docker/build-push-action@v2
#       with:
#         context: .
#         push: ${{ github.event_name != 'pull_request' }}
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}
#     - name: Kuberentes (k8s) cli - kubectl
#       uses: actions-hub/kubectl@v1.24.0
#       env:
#            KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
#       with:
#           args: set image deployment/flexcub-api flexcub-api=${{ steps.meta.outputs.tags }} -n dev
